* El contenido
En especial se debe poner en el front matter:
- el menú ya sea main ó secundario

* Este repositorio es para desarrollo y prueba del theme
Sin embargo el tema en sí, es un subtree apararte 
* Para integrar aplicaciones en elm
1. En la hoja md o html, donde va la aplicación en Elm, se debe poner en el frontmatter elm = "nombre"; siendo nombre de la aplicación.
2. Poner un div class="elm-nombre" para definir el área.
3. Se modifica el package.json para que junto con index también nombre.js se compile a elm en parcel
4. Se crea nombre.js en assets importando la aplicación elm (véase demo.js)
5. La aplicacíon de Elm va en assets/src/nombre/Main.elm
6. Para usar tailwind.el se copia el módulo desde otro folder donde se hace ../doTw4Elm y se tiene que poner en el mismo folder de la aplicación.

* Redactar en bilingue
En el menu aparece la opción de traducido si la hay.
En general se establece

#+begin_src org
#+HUGO_BASE_DIR: ~/Private/elemento/websites/base2/
#+end_src

Y se documenta en sub encabezados los dos archivos poniendo para el de español
#+begin_src org
:PROPERTIES: 
:EXPORT_FILE_NAME: voice-recording
:EXPORT_HUGO_SECTION: /post/
:END:
#+end_src

Asegurando que tiene el mismo nombre
#+begin_src org
:PROPERTIES: 
:EXPORT_FILE_NAME: voice-recording
:EXPORT_HUGO_SECTION: en/post/
:END:
#+end_src

En caso de querer poner nombre diferente
#+begin_src org
:PROPERTIES: 
:EXPORT_FILE_NAME: grabacion-de-voz
:EXPORT_HUGO_SECTION: post
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :translationKey voice 
:END:
#+end_src

Igual se pone el translationKey en inglés así se identifica que son uno pa'l otro.
